# Generated by Django 3.2 on 2022-09-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20220929_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('cpu', models.BooleanField(default=True)),
                ('memory', models.BooleanField(default=True)),
                ('disk', models.BooleanField(default=True)),
                ('network', models.BooleanField(default=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
            ],
            options={
                'verbose_name': 'Performance Monitoring',
                'verbose_name_plural': 'Performance Monitoring',
                'ordering': ['application'],
            },
        ),
        migrations.CreateModel(
            name='AppMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
            ],
            options={
                'verbose_name': 'App Monitoring',
                'verbose_name_plural': 'App Monitoring',
                'ordering': ['application'],
            },
        ),
    ]
