# Generated by Django 3.2 on 2022-10-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_mailserver'),
        ('applications', '0006_application_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='mail_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domains.mailserver'),
        ),
    ]
