# Generated by Django 3.2 on 2022-09-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='monitoring',
            field=models.BooleanField(default=False, verbose_name='Advanced Monitoring?'),
        ),
    ]
