# Generated by Django 3.2 on 2022-09-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_server_monitoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'App Platform',
                'verbose_name_plural': 'App Platforms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Hosting Company',
                'verbose_name_plural': 'Hosting Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='server',
            name='app_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.appplatform'),
        ),
        migrations.AlterField(
            model_name='server',
            name='hosting_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.hostingcompany'),
        ),
    ]
