# Generated by Django 3.2 on 2022-09-22 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0008_clientstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_created_by',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
