# Generated by Django 3.2 on 2022-09-22 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0009_auto_20220922_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['created_at'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_updated_by',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
