# Generated by Django 3.2 on 2022-09-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20220922_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastercredentials',
            name='server',
        ),
        migrations.RemoveField(
            model_name='server',
            name='app_platform',
        ),
        migrations.RemoveField(
            model_name='server',
            name='client',
        ),
        migrations.RemoveField(
            model_name='server',
            name='hosting_company',
        ),
        migrations.RemoveField(
            model_name='sshcredentials',
            name='server',
        ),
        migrations.RemoveField(
            model_name='sslcertificate',
            name='server',
        ),
        migrations.DeleteModel(
            name='AppPlatform',
        ),
        migrations.DeleteModel(
            name='HostingCompany',
        ),
        migrations.DeleteModel(
            name='MasterCredentials',
        ),
    ]
