# Generated by Django 3.2 on 2022-09-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20220923_0813'),
        ('applications', '0002_alter_application_server'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='SshCredentials',
        ),
        migrations.DeleteModel(
            name='SslCertificate',
        ),
    ]
