# Generated by Django 3.2 on 2022-09-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20220923_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
