# Generated by Django 3.2 on 2022-09-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_ticket_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
