# Generated by Django 3.2 on 2022-09-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_ticket_ticket_assigned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time_taken',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
