# Generated by Django 3.2 on 2022-09-23 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0011_auto_20220923_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'App Platform',
                'verbose_name_plural': 'App Platforms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Hosting Company',
                'verbose_name_plural': 'Hosting Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hosted Region')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('server_size', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu', models.CharField(blank=True, max_length=100, null=True)),
                ('memory', models.CharField(blank=True, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, max_length=100, null=True)),
                ('disc_utilization', models.CharField(blank=True, max_length=100, null=True)),
                ('os_details', models.CharField(blank=True, max_length=100, null=True)),
                ('public_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('monitoring', models.BooleanField(default=False, verbose_name='Advanced Monitoring?')),
                ('server_created', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('app_platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.appplatform')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('hosting_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.hostingcompany')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='SslCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provider Name')),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
            options={
                'verbose_name': 'SSL Certificate',
                'verbose_name_plural': 'SSL Certificates',
                'ordering': ['server'],
            },
        ),
        migrations.CreateModel(
            name='SshCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
            options={
                'verbose_name': 'SSH Credentials',
                'verbose_name_plural': 'SSH Credentials',
                'ordering': ['server'],
            },
        ),
        migrations.CreateModel(
            name='MasterCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
            options={
                'verbose_name': 'Master Credentials',
                'verbose_name_plural': 'Master Credentials',
                'ordering': ['server'],
            },
        ),
    ]
