# Generated by Django 3.2 on 2022-09-28 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_is_approved'),
        ('servers', '0002_auto_20220928_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_server', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
            options={
                'verbose_name': 'DNS Details',
                'verbose_name_plural': 'DNS Details',
                'ordering': ['server'],
            },
        ),
    ]
