# Generated by Django 3.2 on 2022-09-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_dnsdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnsrecord',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='dnsrecord',
            name='server',
        ),
        migrations.DeleteModel(
            name='DnsDetails',
        ),
        migrations.DeleteModel(
            name='DnsRecord',
        ),
    ]
