# Generated by Django 3.2 on 2022-10-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_auto_20221004_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Server Consumption'),
        ),
    ]
