# Generated by Django 3.2 on 2022-10-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_alter_server_server_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='monitoring',
        ),
        migrations.AddField(
            model_name='server',
            name='p_monitoring',
            field=models.BooleanField(default=False, verbose_name='Performance Monitoring?'),
        ),
        migrations.AddField(
            model_name='server',
            name='s_monitoring',
            field=models.BooleanField(default=False, verbose_name='Security Monitoring?'),
        ),
        migrations.AddField(
            model_name='server',
            name='u_monitoring',
            field=models.BooleanField(default=False, verbose_name='Real User Monitoring?'),
        ),
        migrations.AddField(
            model_name='server',
            name='w_monitoring',
            field=models.BooleanField(default=False, verbose_name='Website Monitoring?'),
        ),
    ]
