# Generated by Django 3.2 on 2022-10-07 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_is_approved'),
        ('domains', '0003_remove_domain_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_purchased', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Mail Server',
                'verbose_name_plural': 'Mail Servers',
                'ordering': ['name'],
            },
        ),
    ]
