# Generated by Django 3.2 on 2022-09-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20220927_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='public_key',
        ),
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Api Key',
                'verbose_name_plural': 'Api Keys',
                'ordering': ['vendor'],
            },
        ),
    ]
