# Generated by Django 3.2 on 2022-03-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['title'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
